import dotenv from "dotenv";
dotenv.config();

export default {
BOT_TOKEN: process.env.BOT_TOKEN,
ADMIN_ID: process.env.ADMIN_ID,
CPX_API_KEY: process.env.CPX_API_KEY,
CPX_APP_ID: process.env.CPX_APP_ID,
CPX_SECURITY_HASH: process.env.CPX_SECURITY_HASH,
CPX_POSTBACK_SECRET: process.env.CPX_POSTBACK_SECRET,

FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
FIREBASE_APP_ID: process.env.FIREBASE_APP_ID
};
